---
name: enmu_mobile
description: CS458 Semester Project. This app is a university resources app for ENMU.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdfviewer: ^23.1.43
  html: ^0.15.4
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/safe-ride-logo.png
  - assets/images/campus-map-whole.pdf
  - assets/images/campus-map-northwest-us70.pdf
  - assets/images/campus-map-southeast-of-us70.pdf
