name: enmu_mobile
description: CS458 Semester Project. This app is a university resources app for ENMU.
publish_to: 'none' # This will prevent accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0' # This ensures compatibility with Dart SDK versions that support super-parameters

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0      # Upgraded to ^0.9.0 to resolve the version conflict
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdfviewer: ^23.1.43
  flutter_map: ^6.0.1
  http: ^1.0.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/safe-ride-logo.png
