name: enmu_mobile
description: CS458 Semester Project. This app is a university resources app for ENMU.
publish_to: 'none' # This will prevent accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0' # This ensures compatibility with Dart SDK versions that support super-parameters

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6  
  latlong2: ^0.9.0      # Upgraded to ^0.9.0 to resolve the version conflict
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2
  image_gallery_saver: ^2.0.3
  connectivity_plus: ^5.0.1
  syncfusion_flutter_pdfviewer: ^23.1.43
  webview_flutter: ^3.0.3
  flutter_map: ^6.0.1
  http: ^1.0.0
  html: ^0.15.0
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pdfs/

